AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a VPC, EC2 Instances with AutoScaling Group, and S3 Bucket'

Resources:
  # VPC and its components
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Assignment-VPC
  
  # Creates Internet Gateway
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: Assignment-IGW

  # Attaches Internet Gateway to VPC
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Creates Subnets
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: !Select [0, !GetAZs ''] # Selects first AZ
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Assignment-Public-Subnet-1

  PublicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: !Select [1, !GetAZs ''] # Selects second AZ
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Assignment-Public-Subnet-2
  
  # Creates Route Table
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Assignment-Public-Route-Table

  # Creates a Route
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  # Associates Route Table with Subnets
  PublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Security Group for RDP access
  RDPSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow RDP Access'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: Assignment-RDP-SG

  # Launch Template for EC2
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: Assignment-Launch-Template
      LaunchTemplateData:
        ImageId: ami-0c232c9952bd4be59 # Microsoft Windows Server 2022 Base
        InstanceType: t3.micro
        SecurityGroupIds:
          - !Ref RDPSecurityGroup
        KeyName: JosephKey
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: Assignment-Win-Server-Instance
  
  # AutoScaling Group
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: Assignment-AutoScaling-Group
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: '1'
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: Windows EC2 Instance
          PropagateAtLaunch: true

  # S3 Bucket to be used by the instances
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: skillsyncjosephassignment
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: Assignment-S3-Bucket

          
